name: mindease
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.3+2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.0
  intl: ^0.19.0
  just_audio: ^0.9.38
  logger: ^2.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
  uses-material-design: true